### ISSUE TITLE
Use another type than string

### ISSUE THREAD

**Issue by Tilican** [Windastella/godothub#1]
Hi,
This is not really an issue ...

Here you convert all to string ! But number "1" in string contains more bytes than "1" in integer :+1: 

To get better performance, with this library [@gd-com/utils](https://www.npmjs.com/package/@gd-com/utils) you can convert more var or native type than only String :yellow_heart: 

Thanks for your work ! :smile:

**Comment by Windastella** [comment]
Thank you for the heads up. I'm currently optimizing the performance as well as refactoring the code. I will consider using [@gd-com/utils](https://www.npmjs.com/package/@gd-com/utils).

**Comment by Windastella** [comment]
For now, I want to see how far I can push to use JSON format with this project. So thank you for the suggestion. I will open this issue until I decide to implement @gd-com/utils
